fix #131: add backtracing to tester
eoscommunity/Eden pull request #212
Opened 2021-05-18 23:33 UTC by tbfleming

2021-05-19 12:35 UTC, swatanabe commented on programs/cltester/dwarf.cpp
> +                  state.line += eosio::from_bin<eosio::varint32>(s).value;
Wrong variable signed integer format (zigzag vs. LEB128)

2021-05-19 17:52 UTC, tbfleming commented on programs/cltester/main.cpp
> +      if (getcontext(&uc))
changed

2021-05-19 17:52 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +                  state.line += eosio::from_bin<eosio::varint32>(s).value;
changed

2021-05-20 01:11 UTC, tbfleming commented
This didn't go well. The linker failed to relocate the sections in `.debug_line` correctly, plus I see what look like relocation errors in other sections. I was hoping there would be sufficient relocation information elsewhere to make corrections, but I failed to find it probing around with `llvm-dwarfdump` (version 11.0.0). It's still possible it's somewhere (I'm new to dwarf), but if it is, `llvm-dwarfdump --lookup` isn't using it. It generates the same incorrect results that this PR does.

I tried switching to llvm 12 for both compiling and dumping. Many entries have changed (e.g. 00000000 became FFFFFFFF), plus it looks like other things may have changed, so they're obviously working on it, but it still doesn't look right, even with `llvm-dwarfdump --lookup`. I found a message from several years back indicating they use address 0 to indicate reloaction problems; it looks like they switched that. Even then, may of the non-0, non-ffffffff addresses appear off.

2021-05-20 02:10 UTC, tbfleming commented
Example:

```
wasm-objdump -d -r test-token.wasm

...
14a425 func[9738] <eosio::detail::assert_or_throw(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >&&)>:
 ...
 14a476: 10 82 80 80 80 00          | call 2 <eosio_assert_message>
...
```

```
llvm-dwarfdump-12 test-token.wasm --lookup=0x14a476
...
Line info: file 'libraries/abieos/include/eosio/name.hpp', line 196, column 0, start file 'libraries/abieos/include/eosio/name.hpp', start line 195
```

```
lldb-12 -o "image lookup --address 0x14a476" -b test-token.wasm
(lldb) target create "test-token.wasm"
Current executable set to '/home/todd/work/eden/build/test-token.wasm' (wasm32).
(lldb) image lookup --address 0x14a476
      Address: test-token.wasm[0x0014a476] (test-token.wasm.code + 1352822)
      Summary: test-token.wasm`eosio::name eosio::literals::operator"" _n<char, (char)110, (char)101, (char)119, (char)97, (char)99, (char)99, (char)111, (char)117, (char)110, (char)116>() + 15 at name.hpp:196
```

2021-05-20 12:41 UTC, swatanabe commented
The `.debug_info` looks like it's relocated correctly.  The debug_line section is not.

2021-05-20 13:47 UTC, tbfleming commented
After adjusting for the code offset, this part now comes out correct:

```
transaction has exception: Transaction exceeded the current network usage limit imposed on the transaction (3080002)
transaction net usage is too high: 830652 > 524288

0x7fe88bf47a1d 00145df9
/home/todd/work/eden/libraries/abieos/include/eosio/check.hpp:64
0x7fe88bf477eb 00145d60
/home/todd/work/eden/libraries/abieos/include/eosio/check.hpp:140
0x7fe88bf4934e 00146548
/home/todd/work/eden/libraries/eosiolib/tester/tester.cpp:174
0x7fe88bf5526a 001498e4
/home/todd/work/eden/libraries/eosiolib/tester/tester.cpp:382
0x7fe88bf558d2 00149ab7
/home/todd/work/eden/libraries/eosiolib/tester/tester.cpp:389
0x7fe88bf5f239 0014c551
/home/todd/work/eden/libraries/eosiolib/tester/tester.cpp:537
0x7fe88bbf7838 00060897
/home/todd/work/eden/contracts/token/tests/test-token.cpp:28
0x7fe88bbf5f01 00060172
/home/todd/work/eden/contracts/token/tests/test-token.cpp:50
0x7fe88bb6e770 0003af12
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:14261
0x7fe88bb2b637 00028f20
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:14100
0x7fe88bb1abd8 000247c6
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:12959
0x7fe88bb15557 00023062
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:12932
0x7fe88bb1214e 00022231
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:12693
0x7fe88bb3cd25 0002db67
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:13287
0x7fe88bb39fd7 0002cf72
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:13493
0x7fe88bb39686 0002ccdd
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:13449
0x7fe88bbf57a3 0005ff4e
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:13171
0x7fe88bbf5459 0005fe6e
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:17448
0x7fe88c226b83 0020f75f
0x7fe88c226d14 0020f7c7
0x7fe88c226d62 0020f7e7
0x4a658b ffffb982
tester wasm asserted: transaction failed with status hard_fail
```

2021-05-22 17:10 UTC, tbfleming commented
```
transaction has exception: Transaction exceeded the current network usage limit imposed on the transaction (3080002)
transaction net usage is too high: 830652 > 524288

/home/todd/work/eden/libraries/abieos/include/eosio/check.hpp:64: eosio::detail::assert_or_throw(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >&&)
/home/todd/work/eden/libraries/abieos/include/eosio/check.hpp:140: eosio::check(bool, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >&&)
/home/todd/work/eden/libraries/eosiolib/tester/tester.cpp:174: eosio::expect(eosio::transaction_trace const&, char const*)
/home/todd/work/eden/libraries/eosiolib/tester/tester.cpp:382: eosio::test_chain::transact(std::__2::vector<eosio::action, std::__2::allocator<eosio::action> >&&, std::__2::vector<std::__2::variant<std::__2::array<char, 32ul>, std::__2::array<char, 32ul> >, std::__2::allocator<std::__2::variant<std::__2::array<char, 32ul>, std::__2::array<char, 32ul> > > > const&, char const*)
/home/todd/work/eden/libraries/eosiolib/tester/tester.cpp:389: eosio::test_chain::transact(std::__2::vector<eosio::action, std::__2::allocator<eosio::action> >&&, char const*)
/home/todd/work/eden/libraries/eosiolib/tester/tester.cpp:537: eosio::test_chain::set_code(eosio::name, char const*, char const*)
/home/todd/work/eden/contracts/token/tests/test-token.cpp:28: token_tester::token_tester()
/home/todd/work/eden/contracts/token/tests/test-token.cpp:50: ____C_A_T_C_H____T_E_S_T____0()
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:14261: Catch::TestInvokerAsFunction::invoke() const
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:14100: Catch::TestCase::invoke() const
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:12959: Catch::RunContext::invokeActiveTestCase()
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:12932: Catch::RunContext::runCurrentTest(std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >&, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char> >&)
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:12693: Catch::RunContext::runTest(Catch::TestCase const&)
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:13287: Catch::(anonymous namespace)::TestGroup::execute()
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:13493: Catch::Session::runInternal()
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:13449: Catch::Session::run()
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:13171: int Catch::Session::run<char>(int, char const* const*)
/home/todd/work/eden/build/wasm/catch2/include/catch2/catch.hpp:17448: __main_argc_argv
<wasm address 0x0020f75f>
<wasm address 0x0020f7c7>
<wasm address 0x0020f7e7>
tester wasm asserted: transaction failed with status hard_fail
```

2021-05-25 20:14 UTC, swatanabe requested changes

2021-06-08 01:57 UTC, tbfleming commented on libraries/eosiolib/sdk/clsdk-config.cmake
> +    # and non-debug targets.
#235 needs simultaneous release and debug targets for contracts
* The release contracts are what chainlib sees and enforces limits on
* The debug contracts get optionally (user choice at runtime) substituted in for the release contracts at the point of execution

2021-06-08 02:55 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +            switch (extended_opcode)
I haven't run into that in clang's output. I'm adding a note that it only supports DWARF produced by clang 11 or 12 in WASM mode

2021-06-08 02:59 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +                  // fprintf(stderr, "extended opcode %d\n", (int)extended_opcode);
They're ok since they have a length prefix

2021-06-08 03:01 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +      eosio::check(root && root->tag == dw_tag_compile_unit,
I haven't seen that in clang's output. The error message was off though.

2021-06-08 03:12 UTC, tbfleming commented on programs/cltester/main.cpp
> +      auto top_frame = state.backend.get_context()._top_frame;
fixed and note added

2021-06-08 03:12 UTC, tbfleming commented on libraries/abieos/include/eosio/from_bin.hpp
> +   int64_t sleb64_from_bin(S& stream)
changed

2021-06-08 03:13 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +         std::string x = result;
fixed

2021-06-08 03:13 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +      eosio::check(version == lns_version, "bad version in .debug_line");
changed

2021-06-08 03:14 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +         eosio::check(dir <= state.file_names.size(),
fixed

2021-06-08 03:15 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +               if (!attr.name)
changed

2021-06-08 03:15 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +         eosio::check(size < s.remaining(), "variable-length overrun in dwarf entry");
fixed

2021-06-08 11:09 UTC, swatanabe commented on programs/cltester/main.cpp
> +   static void on_unreachable()
A specialization of a member is still a member has access to other private members.

2021-06-08 17:30 UTC, tbfleming commented on programs/cltester/main.cpp
> +   static void on_unreachable()
changed

2021-06-08 20:26 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +      auto initial_state = state;
changed

2021-06-08 20:26 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +         eosio::check(unit_length <= s.remaining(), "bad unit_length in .debug_line");
Added an explicit check

2021-06-08 20:30 UTC, tbfleming commented on programs/cltester/main.cpp
> +   static void on_unreachable()
This style of change didn't work on other cases in #235 since they would need partial specializations, which aren't supported as class members

2021-06-08 20:30 UTC, tbfleming commented on programs/cltester/dwarf.cpp
> +            str = state.include_directories[dir] + "/" + str;
Added a note

2021-06-09 13:29 UTC, swatanabe commented on programs/cltester/main.cpp
> +   static void on_unreachable()
It should work for `parse_section`, at least.  Also, no need to specialize `emit_unreachable`.  The primary template will use your specialization of `on_unreachable`.

2021-06-09 17:06 UTC, tbfleming commented on programs/cltester/main.cpp
> +   static void on_unreachable()
Removed `emit_unreachable`

2021-06-09 17:35 UTC, swatanabe approved these changes

2021-06-09 17:38 UTC, merged